(in-package :net.polyforms.lisp)

(deftest test-utilities ()
  (check
   (test-get-day-name)
   (test-get-month-name)
   (test-get-short-month-name)
   (test-get-absolute-date)
   (test-get-gregorian-date)
   (test-get-day-of-week)
   (test-yesterday)
   (test-tomorrow)))

(deftest test-get-day-name ()
  (check
   (equal (get-day-name -1) nil)
   (equal (get-day-name 0) "Monday")
   (equal (get-day-name 1) "Tuesday")
   (equal (get-day-name 732655) "Sunday")
   (equal (get-day-name 732656) "Monday")
   (equal (get-day-name 732657) "Tuesday")
   (equal (get-day-name '(12 10 2006)) "Sunday")
   (equal (get-day-name '(12 11 2006)) "Monday")
   (equal (get-day-name '(12 12 2006)) "Tuesday")
   (equal (get-day-name) (get-day-name nil))
   (equal (get-day-name) (get-day-name (today)))))

(deftest test-get-month-name ()
  (check
   (equal (get-month-name -1) nil)
   (equal (get-month-name 0) nil)
   (equal (get-month-name 1) "January")
   (equal (get-month-name 12) "December")
   (equal (get-month-name 13) "January")
   (equal (get-month-name 732656) "December")
   (equal (get-month-name 732677) "January")
   (equal (get-month-name '(12 11 2006)) "December")
   (equal (get-month-name '(01 01 2007)) "January")
   (equal (get-month-name) (get-month-name nil))
   (equal (get-month-name) (get-month-name (today)))))

(deftest test-get-short-month-name ()
  (check
   (equal (get-short-month-name -1) nil)
   (equal (get-short-month-name 0) nil)
   (equal (get-short-month-name 1) "jan")
   (equal (get-short-month-name 12) "dec")
   (equal (get-short-month-name 13) "jan")
   (equal (get-short-month-name 732656) "dec")
   (equal (get-short-month-name 732677) "jan")
   (equal (get-short-month-name '(12 11 2006)) "dec")
   (equal (get-short-month-name '(01 01 2007)) "jan")
   (equal (get-short-month-name) (get-short-month-name nil))
   (equal (get-short-month-name) (get-short-month-name (today)))))

(deftest test-get-absolute-date ()
  (check
   (equal (get-absolute-date -1) -1)
   (equal (get-absolute-date 0) 0)
   (equal (get-absolute-date 732656) 732656)
   (equal (get-absolute-date 732677) 732677)
   (equal (get-absolute-date '(12 10 2006)) 732655)
   (equal (get-absolute-date '(12 11 2006)) 732656)
   (equal (get-absolute-date '(01 01 2007)) 732677)
   (equal (get-absolute-date) (get-absolute-date nil))
   (equal (get-absolute-date) (get-absolute-date (today)))))

(deftest test-get-gregorian-date ()
  (check
   (equal (get-gregorian-date -1) '(12 30 0))
   (equal (get-gregorian-date 0) '(12 31 0))
   (equal (get-gregorian-date 732656) '(12 11 2006))
   (equal (get-gregorian-date 732677) '(01 01 2007))
   (equal (get-gregorian-date '(12 10 2006)) '(12 10 2006))
   (equal (get-gregorian-date '(12 11 2006)) '(12 11 2006))
   (equal (get-gregorian-date '(01 01 2007)) '(01 01 2007))
   (equal (get-gregorian-date) (get-gregorian-date nil))
   (equal (get-gregorian-date) (get-gregorian-date (today)))))

(deftest test-get-day-of-week ()
  (check
   (equal (get-day-of-week -1) nil)
   (equal (get-day-of-week 0) 6)
   (equal (get-day-of-week 732656) 0)
   (equal (get-day-of-week 732677) 0)
   (equal (get-day-of-week '(12 10 2006)) 6)
   (equal (get-day-of-week '(12 11 2006)) 0)
   (equal (get-day-of-week '(01 01 2007)) 0)
   (equal (get-day-of-week) (get-day-of-week nil))
   (equal (get-day-of-week) (get-day-of-week (today)))))

(deftest test-yesterday ()
  (check
   (equal (yesterday) (1- (today)))
   (equal (today) (1+ (yesterday)))))

(deftest test-tomorrow ()
  (check
   (equal (tomorrow) (1+ (today)))
   (equal (today) (1- (tomorrow)))))
